matrix:
  include:
  - os: osx
    env: TARGET=mac
    osx_image: xcode9.2
    language: node_js
    node_js: '9'
  - os: windows
    env: TARGET=windows
    services: docker
    language: node_js
    node_js: '9'
  - os: linux
    env: TARGET=linux
    language: node_js
    node_js: '9'
cache: false
before_install:
- |
  unset TRAVIS_COMMIT_MESSAGE;
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
    export PATH="/tmp/git-lfs:$PATH"
  elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get -qq update
    sudo apt-get install -y libsecret-1-dev
    sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
    export PATH="$HOME/.yarn/bin:$PATH"
  fi
before_script:
- git lfs pull
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then unset WIN_CSC_LINK; unset CSC_LINK; fi
script:
- |
  if [ "$TARGET" == "windows" ]; then
    # Remove any special characters before adding to our list of ENVs
    # https://github.com/electron-userland/electron-builder/issues/2450#issuecomment-421788155
    ENVS=`env | grep -iE '(DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_|TARGET)([A-Z]|_)*=' | sed -n '/^[^\t]/s/=.*//p' | sed '/^$/d' | sed 's/^/-e /g' | tr '\n' ' '`
    docker run $ENVS --rm \
      -v ${PWD}:/project \
      electronuserland/builder:wine \
      /bin/bash -c "env | grep -v '\r' | grep -iE 'DEBUG|TARGET|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_|WIN_' && yarn --link-duplicates --pure-lockfile && yarn build --win --publish onTag";
  fi
- if [ "$TARGET" == "appx" ]; then yarn build --publish onTag; fi
- if [ "$TARGET" == "mac" ]; then yarn build --publish onTag; fi
- if [ "$TARGET" == "linux" ]; then yarn --link-duplicates --pure-lockfile && yarn
  build --linux --publish onTag; fi
addons:
  artifacts:
    working_dir: dist
    paths:
    - $(git ls-files -o dist/{*.dmg,*.exe,*.deb} | tr "\n" ":")
    target_paths:
    - "/app/build-${TRAVIS_BUILD_NUMBER}_commit-${TRAVIS_COMMIT:0:7}$([ ! -z ${TRAVIS_TAG}
      ] && echo _tag-${TRAVIS_TAG})"
env:
  global:
  - ARTIFACTS_REGION=us-east-1
  - ARTIFACTS_BUCKET=build.lbry.io
  - DANGER_GITHUB_API_TOKEN=f8b612049cbda985c251e18ae36c7a2b9c6c92df
  - ARTIFACTS_DEBUG=1
  - WIN_CSC_LINK=https://s3.amazonaws.com/files.lbry.io/cert/win-csc-2018-2019-08.p12
  - CSC_LINK=https://s3.amazonaws.com/files.lbry.io/cert/osx-cert.p12
